/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/notebooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notebooks Endpoint */
        get: operations["list_notebooks_endpoint_notebooks_get"];
        put?: never;
        /** Create Notebook */
        post: operations["create_notebook_notebooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notebooks/{notebook_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notebook */
        get: operations["get_notebook_notebooks__notebook_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notebooks/{notebook_path}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Notebook */
        post: operations["run_notebook_notebooks__notebook_path__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates Endpoint */
        get: operations["list_templates_endpoint_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_jobs__job_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/artifacts/{artifact_path}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Artifact */
        get: operations["preview_artifact_jobs__job_id__artifacts__artifact_path__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/artifacts/{artifact_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_jobs__job_id__artifacts__artifact_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sql/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_sql_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sql/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved */
        get: operations["list_saved_sql_saved_get"];
        put?: never;
        /** Create Saved */
        post: operations["create_saved_sql_saved_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sql/saved/{saved_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Saved */
        delete: operations["delete_saved_sql_saved__saved_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sql/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History */
        get: operations["list_history_sql_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tables Endpoint */
        get: operations["list_tables_endpoint_catalog_tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/tables/{schema_name}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Table Detail */
        get: operations["get_table_detail_catalog_tables__schema_name___name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/git/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status Endpoint */
        get: operations["status_endpoint_git_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/git/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log Endpoint */
        get: operations["log_endpoint_git_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactEntryOut */
        ArtifactEntryOut: {
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Last Modified
             * Format: date-time
             */
            last_modified: string;
            /** Previewable */
            previewable: boolean;
        };
        /** ArtifactListOut */
        ArtifactListOut: {
            /** Items */
            items: components["schemas"]["ArtifactEntryOut"][];
            /** Total */
            total: number;
        };
        /** ArtifactPreviewOut */
        ArtifactPreviewOut: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: unknown[][];
            /** Total Rows */
            total_rows: number;
            /** Truncated */
            truncated: boolean;
        };
        /** CancelResponse */
        CancelResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /** ColumnEntryOut */
        ColumnEntryOut: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Nullable */
            nullable: boolean;
        };
        /** CreateNotebookRequest */
        CreateNotebookRequest: {
            /** Template */
            template: string;
            /** Name */
            name: string;
        };
        /** GitCommitOut */
        GitCommitOut: {
            /** Sha */
            sha: string;
            /** Short Sha */
            short_sha: string;
            /** Author */
            author: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Message */
            message: string;
        };
        /** GitLogOut */
        GitLogOut: {
            /** Items */
            items: components["schemas"]["GitCommitOut"][];
            /** Total */
            total: number;
        };
        /** GitStatusOut */
        GitStatusOut: {
            /** Is Repo */
            is_repo: boolean;
            /** Branch */
            branch: string | null;
            /** Commit Sha */
            commit_sha: string | null;
            /** Dirty */
            dirty: boolean;
            /** Ahead */
            ahead: number;
            /** Behind */
            behind: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobListOut */
        JobListOut: {
            /** Items */
            items: components["schemas"]["JobRunOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** JobRunOut */
        JobRunOut: {
            /** Id */
            id: string;
            /** Notebook Path */
            notebook_path: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Triggered By */
            triggered_by: string;
            /** Git Commit Sha */
            git_commit_sha: string | null;
            /** Git Dirty */
            git_dirty: boolean;
            /** Error Message */
            error_message: string | null;
            /** Log Path */
            log_path: string | null;
            /** Artifact Path */
            artifact_path: string | null;
            /** Mcp Run Id */
            mcp_run_id: string | null;
            /** Parameters Json */
            parameters_json: string;
            /** Parent Run Id */
            parent_run_id: string | null;
            /** Schedule Id */
            schedule_id: string | null;
            /** Timeout Seconds */
            timeout_seconds: number;
        };
        /** NotebookDetailOut */
        NotebookDetailOut: {
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Last Modified
             * Format: date-time
             */
            last_modified: string;
            /** Recent Runs */
            recent_runs: components["schemas"]["JobRunOut"][];
        };
        /** NotebookEntryOut */
        NotebookEntryOut: {
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Last Modified
             * Format: date-time
             */
            last_modified: string;
        };
        /** NotebookListOut */
        NotebookListOut: {
            /** Items */
            items: components["schemas"]["NotebookEntryOut"][];
            /** Total */
            total: number;
        };
        /** QueryHistoryListOut */
        QueryHistoryListOut: {
            /** Items */
            items: components["schemas"]["QueryHistoryOut"][];
            /** Total */
            total: number;
        };
        /** QueryHistoryOut */
        QueryHistoryOut: {
            /** Id */
            id: number;
            /** Sql */
            sql: string;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Row Count */
            row_count: number | null;
            /** Error Message */
            error_message: string | null;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Sql */
            sql: string;
            /**
             * Row Limit
             * @default 1000
             */
            row_limit: number;
            /**
             * Timeout Seconds
             * @default 30
             */
            timeout_seconds: number;
        };
        /** QueryResultOut */
        QueryResultOut: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: unknown[][];
            /** Row Count */
            row_count: number;
            /** Truncated */
            truncated: boolean;
            /** Duration Ms */
            duration_ms: number;
        };
        /** RunNotebookRequest */
        RunNotebookRequest: {
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /**
             * Timeout Seconds
             * @default 300
             */
            timeout_seconds: number;
            /**
             * Triggered By
             * @default api
             */
            triggered_by: string;
        };
        /** SavedQueryIn */
        SavedQueryIn: {
            /** Name */
            name: string;
            /** Sql */
            sql: string;
        };
        /** SavedQueryListOut */
        SavedQueryListOut: {
            /** Items */
            items: components["schemas"]["SavedQueryOut"][];
            /** Total */
            total: number;
        };
        /** SavedQueryOut */
        SavedQueryOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Sql */
            sql: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TableDetailOut */
        TableDetailOut: {
            /** Schema */
            schema: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Columns */
            columns: components["schemas"]["ColumnEntryOut"][];
            /** Row Count */
            row_count: number | null;
            /** Sample Columns */
            sample_columns: string[];
            /** Sample Rows */
            sample_rows: unknown[][];
        };
        /** TableEntryOut */
        TableEntryOut: {
            /** Schema */
            schema: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
        };
        /** TableListOut */
        TableListOut: {
            /** Items */
            items: components["schemas"]["TableEntryOut"][];
            /** Total */
            total: number;
        };
        /** TemplateEntryOut */
        TemplateEntryOut: {
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Last Modified
             * Format: date-time
             */
            last_modified: string;
        };
        /** TemplateListOut */
        TemplateListOut: {
            /** Items */
            items: components["schemas"]["TemplateEntryOut"][];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_notebooks_endpoint_notebooks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotebookListOut"];
                };
            };
        };
    };
    create_notebook_notebooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNotebookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotebookEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notebook_notebooks__notebook_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotebookDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_notebook_notebooks__notebook_path__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_path: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunNotebookRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_endpoint_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListOut"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string | null;
                notebook_path?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_jobs__job_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_artifact_jobs__job_id__artifacts__artifact_path__preview_get: {
        parameters: {
            query?: {
                rows?: number;
            };
            header?: never;
            path: {
                job_id: string;
                artifact_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_jobs__job_id__artifacts__artifact_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                artifact_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_sql_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_sql_saved_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedQueryListOut"];
                };
            };
        };
    };
    create_saved_sql_saved_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedQueryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedQueryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_saved_sql_saved__saved_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                saved_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_sql_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryHistoryListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tables_endpoint_catalog_tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableListOut"];
                };
            };
        };
    };
    get_table_detail_catalog_tables__schema_name___name__get: {
        parameters: {
            query?: {
                sample_rows?: number;
            };
            header?: never;
            path: {
                schema_name: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_endpoint_git_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitStatusOut"];
                };
            };
        };
    };
    log_endpoint_git_log_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
